template: testify
structname: "{{ .Mock }}{{ .InterfaceName }}"
pkgname: mocks
dir: "mocks"
filename: "{{ .SrcPackageName }}_mocks.go"

packages:
  github.com/k6zma/avito-lab1/internal/domain/repositories:
    config:
      all: true
  github.com/k6zma/avito-lab1/internal/domain/models:
    config:
      all: true
